name: test_install
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lorislab/install-samo-action@main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: samo project version

