name: test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Project version
        uses: lorislab/samo-action@v0.1.0-alpha2
        with:
          args: samo project version
      - name: Project version
        uses: lorislab/samo-action@v0.1.0-alpha2
        with:
            args: echo "FOO=$(samo project version)" >> $GITHUB_ENV            
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.FOO }}"
