name: test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Project version
        id: version
        uses: lorislab/samo-action@main
        with:
          args: samo project version
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.version.outputs.stdout }}"
      - name: Project version
        uses: lorislab/samo-action@main
        with:
          entrypoint: samo
          args: project version
