name: test
on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Project version
        run: |
          mkdir target
          echo '${{ toJSON(github) }}' > 'target/github.json'
          echo '{"key": ${{ github.event.pull_request.number }}, "branch":"${{ github.head_ref }}", "base": "${{ github.base_ref }}" }' > 'target/github-sonar.json'         

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: target
          retention-days: 1
          if-no-files-found: ignore
