name: test_install
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lorislab/install-samo-action@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: samo project version
      - id: version
        run: echo "stdout=$(samo project version)" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.version.outputs.stdout }}"

