name: build-release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          token: ${{ secrets.TEST_PAT }}
      - name: Project version
        id: version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.version.outputs.stdout }}"

