name: Create release
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check
        run: |
          echo ${{ github.ref_name }}    
      - name: Project version
        id: version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.version.outputs.stdout }}"
      - name: Config git
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create release
        uses: lorislab/samo-action@v1.0.0
        with:
          entrypoint: samo
          args: project release