on:
  workflow_dispatch:

jobs
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Project version
        id: version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
